# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10OvurUz-ouf1IbHK5SwWPcxQf2QjR1Ww
"""

import torch
import torch.nn as nn
import torch.optim as optim
import kagglehub
from torch.utils.data import DataLoader, TensorDataset
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np
from PIL import Image
import os
import pandas as pd

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


path = kagglehub.dataset_download("sumn2u/garbage-classification-v2")


print("Path to dataset files:", path)

def img_to_matrix(img):
    img = img.convert('RGB')

    original_width, original_height = img.size

    ratio = min(128 / original_width, 128 / original_height)
    new_width = int(original_width * ratio)
    new_height = int(original_height * ratio)

    img = img.resize((new_width, new_height), Image.LANCZOS)

    new_img = Image.new('RGB', (128, 128), (0, 0, 0))

    paste_x = (128 - new_width) // 2
    paste_y = (128 - new_height) // 2

    new_img.paste(img, (paste_x, paste_y))

    matrix = np.array(new_img)

    matrix = matrix / 255.0

    flattened_matrix = matrix.reshape(-1)

    return flattened_matrix

base_path = os.path.join(path, "original")

image_data = []
image_labels = []

allowed_categories = ['metal', 'plastic', 'glass', 'paper', 'organic']

for folder_name in os.listdir(base_path):
    if folder_name not in allowed_categories:
        print(f"Skipping folder: {folder_name} (not in allowed categories)")
        continue

    folder_path = os.path.join(base_path, folder_name)

    if os.path.isdir(folder_path):
        for file_name in os.listdir(folder_path):
            file_path = os.path.join(folder_path, file_name)

            try:
                img = Image.open(file_path)
                matrix = img_to_matrix(img)

                image_data.append(matrix)
                image_labels.append(folder_name)
            except Exception as e:
                print(f"Could not process file {file_path}: {e}")

df = pd.DataFrame({"image_matrix": image_data, "class_label": image_labels})

print("DataFrame created with", len(df), "images.")

X_train, X_test, y_train, y_test = train_test_split(
    df['image_matrix'], df['class_label'], test_size=0.2, random_state=42, stratify=df['class_label']
)

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

allowed_categories = ['metal', 'plastic', 'glass', 'paper', 'organic']
label_to_int = {label: i for i, label in enumerate(allowed_categories)}

X_train_np = np.stack(X_train.values) / 255.0
X_test_np = np.stack(X_test.values) / 255.0

X_train_flat = X_train_np.reshape(X_train_np.shape[0], -1)
X_test_flat = X_test_np.reshape(X_test_np.shape[0], -1)

y_train_encoded = y_train.map(label_to_int).values
y_test_encoded = y_test.map(label_to_int).values

X_train_t = torch.tensor(X_train_flat, dtype=torch.float32).to(device)
y_train_t = torch.tensor(y_train_encoded, dtype=torch.long).to(device)
X_test_t = torch.tensor(X_test_flat, dtype=torch.float32).to(device)
y_test_t = torch.tensor(y_test_encoded, dtype=torch.long).to(device)

train_dataset = TensorDataset(X_train_t, y_train_t)
test_dataset = TensorDataset(X_test_t, y_test_t)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

class SimpleNN(nn.Module):
    def __init__(self, num_classes=5):
        super().__init__()
        # Свёрточные слои
        self.conv1 = nn.Conv2d(in_channels=3, out_channels=5, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(in_channels=5, out_channels=7, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(in_channels=7, out_channels=9, kernel_size=3, padding=1)
        self.conv4 = nn.Conv2d(in_channels=9, out_channels=11, kernel_size=3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)   # уменьшает размер вдвое

        self.fc1 = nn.Linear(704, 128)
        self.fc2 = nn.Linear(128, num_classes)

        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.2)
        self.dropout2d = nn.Dropout2d(0.2)

    def forward(self, x):
        x = x.view(-1, 3, 128, 128)

        # Свёртки + пулинг
        x = self.pool(self.relu(self.conv1(x)))
        x = self.pool(self.relu(self.conv2(x)))
        x = self.pool(self.relu(self.conv3(x)))
        x = self.pool(self.relu(self.conv4(x)))

        # Разворачиваем в плоский вектор
        x = x.view(x.size(0), -1)

        # Полносвязные слои
        x = self.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return x

model = SimpleNN(num_classes=5).to(device)
criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(model.parameters(), lr=0.001)

# Обучение
num_epochs = 100

for epoch in range(num_epochs):
    model.train()   # переключаем модель в train-режим (dropout активен)
    running_loss = 0.0

    for inputs, labels in train_loader:
        # Обнуляем градиенты, накопленные за предыдущий батч
        optimizer.zero_grad()

        # Прямой проход: получаем логиты
        outputs = model(inputs)

        # Вычисляем значение функции потерь между предсказаниями и истинными метками
        loss = criterion(outputs, labels)

        # Обратное распространение (вычисляем градиенты)
        loss.backward()

        # Обновляем веса сети (один шаг оптимизатора)
        optimizer.step()

        # Суммируем потери за батч (для вывода среднего по эпохе)
        running_loss += loss.item()

    # ---------- РЕЖИМ ОЦЕНКИ (на тестовой выборке) ----------
    model.eval()    # переключаем в eval-режим (dropout выключается)
    correct = 0
    total = 0

    # Отключаем вычисление градиентов — это экономит память и ускоряет расчёты
    with torch.no_grad():
        for inputs, labels in test_loader:
            outputs = model(inputs)                # получаем логиты
            _, pred = torch.max(outputs, 1)        # выбираем класс с максимальной вероятностью
            total += labels.size(0)                # общее количество примеров в батче
            correct += (pred == labels).sum().item()  # число правильных ответов

    # Считаем точность (accuracy) в процентах
    acc = 100 * correct / total

    # Печатаем статистику по эпохе
    print(f'Epoch {epoch+1:2d} | Loss: {running_loss/len(train_loader):.4f} | Test Acc: {acc:.2f}%')

# ----------------------------------------------------------------------
# После завершения обучения модель готова к использованию.
# Можно сохранить веса через torch.save(model.state_dict(), 'model.pth')
# и загружать позже.
# ----------------------------------------------------------------------

#Сохранение модели
import joblib

torch.save(model.state_dict(), 'model_weights.pth')

print("Модель сохранена.")