# -*- coding: utf-8 -*-
"""Функция предсказания.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FYzY7rHMU7nIG7_1i9G3iNN4NkMzlH-Y
"""

def predict_image_class(image_path):
    import torch.nn as nn
    from PIL import Image
    import torch
    import numpy as np

    def img_to_matrix(img):
      img = img.convert('RGB')

      original_width, original_height = img.size

      ratio = min(128 / original_width, 128 / original_height)
      new_width = int(original_width * ratio)
      new_height = int(original_height * ratio)

      img = img.resize((new_width, new_height), Image.LANCZOS)

      new_img = Image.new('RGB', (128, 128), (0, 0, 0))

      paste_x = (128 - new_width) // 2
      paste_y = (128 - new_height) // 2

      new_img.paste(img, (paste_x, paste_y))

      matrix = np.array(new_img)

      matrix = matrix / 255.0

      flattened_matrix = matrix.reshape(-1)

      return flattened_matrix

    class SimpleNN(nn.Module):
      def __init__(self, num_classes=5):
          super().__init__()
          # Свёрточные слои
          self.conv1 = nn.Conv2d(in_channels=3, out_channels=5, kernel_size=3, padding=1)
          self.conv2 = nn.Conv2d(in_channels=5, out_channels=7, kernel_size=3, padding=1)
          self.conv3 = nn.Conv2d(in_channels=7, out_channels=9, kernel_size=3, padding=1)
          self.conv4 = nn.Conv2d(in_channels=9, out_channels=11, kernel_size=3, padding=1)
          self.pool = nn.MaxPool2d(2, 2)   # уменьшает размер вдвое

          self.fc1 = nn.Linear(704, 128)
          self.fc2 = nn.Linear(128, num_classes)

          self.relu = nn.ReLU()
          self.dropout = nn.Dropout(0.2)
          self.dropout2d = nn.Dropout2d(0.2)

      def forward(self, x):
          x = x.view(-1, 3, 128, 128)

          # Свёртки + пулинг
          x = self.pool(self.relu(self.conv1(x)))
          x = self.pool(self.relu(self.conv2(x)))
          x = self.pool(self.relu(self.conv3(x)))
          x = self.pool(self.relu(self.conv4(x)))

          # Разворачиваем в плоский вектор
          x = x.view(x.size(0), -1)

          # Полносвязные слои
          x = self.relu(self.fc1(x))
          x = self.dropout(x)
          x = self.fc2(x)
          return x

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    allowed_categories = ['metal', 'plastic', 'glass', 'paper', 'organic']
    label_to_int = {label: i for i, label in enumerate(allowed_categories)}
    loaded_model = SimpleNN(num_classes=5)
    loaded_model.load_state_dict(torch.load('model_weights.pth'))
    loaded_model.to(device)

    loaded_model.eval()

    if isinstance(image_path, str):
        img = Image.open(image_path)
    elif isinstance(image_path, Image.Image):
        img = image_path
    else:
        print("Передайте путь до файла!")
        return None

    matrix = img_to_matrix(img)
    processed_image = torch.tensor(matrix.reshape(3, 128, 128), dtype=torch.float32).unsqueeze(0).to(device)
    loaded_model.eval()
    with torch.no_grad():
        outputs = loaded_model(processed_image)
        _, predicted_idx = torch.max(outputs, 1)
    int_to_label = {i: label for label, i in label_to_int.items()}
    predicted_label = int_to_label.get(predicted_idx.item())

    return predicted_label